language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         

env:
- TRAVIS_TAG="1.0" PROJECT_NAME="pipeline" UNITY_PROJECT_PATH="pipeline" UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache" 


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- rvm get stable
- chmod a+x ./Scripts/*.sh

install:
- cat /etc/hosts
- ./Scripts/install.sh

script:
- ./Scripts/build.sh

deploy:
  provider: releases
  api_key: 610f2f655af6f4022e31b7e879d3bd58669e17d7
  file: pipeline-v1.0-b31.unitypackage
  skip_cleanup: true
  overwrite: true
  on: 
    tags: true 
