language: objective-c

before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh

branches:
  only:
    - master
    - develop
    
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: develop