language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

before_install:
- rvm get stable
- chmod a+x ./Scripts/*.sh

install:
- cat /etc/hosts
- ./Scripts/install.sh

script:
- ./Scripts/build.sh

after_success:
- ./Scripts/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 